angular.module('palladio.services',
	[	'palladio.services.date',
		'palladio.services.spinner',
		'palladio.services.parse',
		'palladio.services.validation',
		'palladio.services.exception',
		'palladio.services.export',
		'palladio.services.data',
		'palladio.services.date',
		'palladio.services.load' ]);